/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Futterrudel;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-13T11:05:20.560Z")

@Api(value = "futterrudel", description = "the futterrudel API")
public interface FutterrudelApi {

    @ApiOperation(value = "", nickname = "entfernePersonAusRudel", notes = "", response = Futterrudel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "futterrudel", response = Futterrudel.class) })
    @RequestMapping(value = "/futterrudel/{fid}/werisstwas/{wid}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Futterrudel> entfernePersonAusRudel(@ApiParam(value = "futterrudelID",required=true) @PathVariable("fid") Integer fid,@ApiParam(value = "WerIsstWasID",required=true) @PathVariable("wid") Integer wid);


    @ApiOperation(value = "", nickname = "entferneRudel", notes = "", response = Futterrudel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "futterrudel", response = Futterrudel.class) })
    @RequestMapping(value = "/futterrudel/{fid}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Futterrudel> entferneRudel(@ApiParam(value = "futterrudelID",required=true) @PathVariable("fid") Integer fid);


    @ApiOperation(value = "hinzufügen eines neuen futterrudels", nickname = "futterrudelAnlegen", notes = "", response = Futterrudel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "futterrudelAnlegen", response = Futterrudel.class) })
    @RequestMapping(value = "/futterrudel",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Futterrudel> futterrudelAnlegen(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Futterrudel body);


    @ApiOperation(value = "alle futterrudel bekommen", nickname = "getfutterrudel", notes = "", response = Futterrudel.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "allefutterrudel", response = Futterrudel.class, responseContainer = "List") })
    @RequestMapping(value = "/futterrudel",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Futterrudel>> getfutterrudel();

}
