/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Futterrudel;
import io.swagger.model.Gericht;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-13T11:05:20.560Z")

@Api(value = "gerichte", description = "the gerichte API")
public interface GerichteApi {

    @ApiOperation(value = "", nickname = "getgerichte", notes = "", response = Gericht.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "allegerichte", response = Gericht.class, responseContainer = "List") })
    @RequestMapping(value = "/gerichte",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Gericht>> getgerichte();


    @ApiOperation(value = "hinzufügen eines neuen gerichtes", nickname = "putGericht", notes = "", response = Futterrudel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "succsessfull", response = Futterrudel.class) })
    @RequestMapping(value = "/gerichte",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Futterrudel> putGericht(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Gericht body);

}
